.travis.yml: test travis with docker

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,58 +5,75 @@ language: python
 python:
   - "2.7"
 
+services:
+  - docker
+
 env:
-  - ANSIBLE_VERSION=latest
-  - ANSIBLE_VERSION=2.4.1.0
-  - ANSIBLE_VERSION=2.4.0.0
-  - ANSIBLE_VERSION=2.3.2.0
-  - ANSIBLE_VERSION=2.3.1.0
-  - ANSIBLE_VERSION=2.3.0.0
-  - ANSIBLE_VERSION=2.2.3.0
-  - ANSIBLE_VERSION=2.2.2.0
-  - ANSIBLE_VERSION=2.2.1.0
-  - ANSIBLE_VERSION=2.2.0.0
-  - ANSIBLE_VERSION=2.1.6
-  - ANSIBLE_VERSION=2.1.5
-  - ANSIBLE_VERSION=2.1.4
-  - ANSIBLE_VERSION=2.1.3
-  - ANSIBLE_VERSION=2.1.2
-  - ANSIBLE_VERSION=2.1.1.0
-  - ANSIBLE_VERSION=2.1.0.0
-  - ANSIBLE_VERSION=2.0.2.0
-  - ANSIBLE_VERSION=2.0.1.0
-  - ANSIBLE_VERSION=2.0.0.2
-  - ANSIBLE_VERSION=2.0.0.1
-  - ANSIBLE_VERSION=2.0.0.0
+  - DOCKER_DISTRO: "debian:jessie"
+    ANSIBLE_VERSION: latest
+  - DOCKER_DISTRO="debian:jessie" ANSIBLE_VERSION=2.4.0.0
+  - DOCKER_DISTRO="debian:jessie" ANSIBLE_VERSION=2.3.0.0
+  - DOCKER_DISTRO="debian:jessie" ANSIBLE_VERSION=2.2.0.0
+  - DOCKER_DISTRO="debian:jessie" ANSIBLE_VERSION=2.1.0.0
+  - DOCKER_DISTRO="debian:jessie" ANSIBLE_VERSION=2.0.0.0
+  - DOCKER_DISTRO="ubuntu:trusty" ANSIBLE_VERSION=latest
+  - DOCKER_DISTRO="ubuntu:trusty" ANSIBLE_VERSION=2.4.0.0
+  - DOCKER_DISTRO="ubuntu:trusty" ANSIBLE_VERSION=2.3.0.0
+  - DOCKER_DISTRO="ubuntu:trusty" ANSIBLE_VERSION=2.2.0.0
+  - DOCKER_DISTRO="ubuntu:trusty" ANSIBLE_VERSION=2.1.0.0
+  - DOCKER_DISTRO="ubuntu:trusty" ANSIBLE_VERSION=2.0.0.0
 
 branches:
   only:
     - master
+    - travis_tests
 
 before_install:
   - sudo apt-get update -qq
+  - docker pull "$DOCKER_DISTRO"
 
-install:
-  # Install Ansible.
+before_script:
+  - container_id=$(mktemp)
   - >
+    'docker run --detach
+    --volume="${PWD}":/etc/ansible/roles/rkhunter:ro
+    $DOCKER_DISTRO "/bin/bash"
+    > "${container_id}"'
+  - >
+    'docker exec "$(cat ${container_id})"
+    apt-get update &&
+    apt-get upgradde -y
+    apt-get install python python-pip'
+  - >
+    'docker exec "$(cat ${container_id})"
     if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible;
     else pip install ansible==$ANSIBLE_VERSION; fi
-  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi
+    '
+  - >
+    'docker exec "$(cat ${container_id})"
+    if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi
+    '
 
 script:
   # Check the role/playbook's syntax.
-  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
+  - >
+    'docker exec "$(cat ${container_id})"
+    ansible-playbook -i tests/inventory tests/test.yml --syntax-check'
 
   # Run the role/playbook with ansible-playbook.
-  - ansible-playbook -i tests/inventory tests/test.yml -vvvv
+  - >
+    'docker exec "$(cat ${container_id})"
+    ansible-playbook -i tests/inventory tests/test.yml -vvvv'
 
   # Run the role/playbook again, checking to make sure it's idempotent.
   - >
+    'docker exec "$(cat ${container_id})"
     ansible-playbook -i tests/inventory tests/test.yml
-    | grep -q 'changed=0.*failed=0'
-    && (echo 'Idempotence test: pass' && exit 0)
-    || (echo 'Idempotence test: fail' && exit 1)
+    | grep -q "changed=0.*failed=0"
+    && (echo "Idempotence test: pass" && exit 0)
+    || (echo "Idempotence test: fail" && exit 1)'
 
   - >
+    'docker exec "$(cat ${container_id})"
     if [ "$ANSIBLE_VERSION" = "latest" ]; then
-    ansible-lint tests/test.yml || true; fi
+    ansible-lint tests/test.yml || true; fi'
