add build-essential

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -41,40 +41,40 @@ before_script:
     --volume="${PWD}":/etc/ansible/roles/rkhunter:ro
     $DOCKER_DISTRO "/lib/systemd/systemd" > "${container_id}"
   - >
-    docker exec "$(cat ${container_id})" bash -c '
+    docker exec "$(cat ${container_id})" bash -c "
     apt-get update &&
     apt-get upgrade -y &&
-    apt-get install -y python python-pip
-    '
+    apt-get install -y build-essential python-pip python-dev &&
+    pip install --upgrade setuptools"
   - >
     docker exec "$(cat ${container_id})" bash -c "
     if [ \"$ANSIBLE_VERSION\" = \"latest\" ]; then pip install ansible;
     else pip install ansible==$ANSIBLE_VERSION; fi
     "
   - >
-    docker exec "$(cat ${container_id})"
-    if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi
+    docker exec "$(cat ${container_id})" bash -c "
+    if [ \"$ANSIBLE_VERSION\" = \"latest\" ]; then pip install ansible-lint; fi"
 
 script:
   # Check the role/playbook's syntax.
   - >
-    'docker exec "$(cat ${container_id})"
-    ansible-playbook -i tests/inventory tests/test.yml --syntax-check'
+    docker exec "$(cat ${container_id})"
+    ansible-playbook -i tests/inventory tests/test.yml --syntax-check
 
   # Run the role/playbook with ansible-playbook.
   - >
-    'docker exec "$(cat ${container_id})"
-    ansible-playbook -i tests/inventory tests/test.yml -vvvv'
+    docker exec "$(cat ${container_id})"
+    ansible-playbook -i tests/inventory tests/test.yml -vvvv
 
   # Run the role/playbook again, checking to make sure it's idempotent.
   - >
-    'docker exec "$(cat ${container_id})"
+    docker exec "$(cat ${container_id})" bash -c "
     ansible-playbook -i tests/inventory tests/test.yml
-    | grep -q "changed=0.*failed=0"
-    && (echo "Idempotence test: pass" && exit 0)
-    || (echo "Idempotence test: fail" && exit 1)'
+    | grep -q 'changed=0.*failed=0'
+    && (echo 'Idempotence test: pass' && exit 0)
+    || (echo 'Idempotence test: fail' && exit 1)"
 
   - >
-    'docker exec "$(cat ${container_id})"
-    if [ "$ANSIBLE_VERSION" = "latest" ]; then
-    ansible-lint tests/test.yml || true; fi'
+    docker exec "$(cat ${container_id})" bash -c "
+    if [ \"$ANSIBLE_VERSION\" = \"latest\" ]; then
+    ansible-lint tests/test.yml || true; fi"
